In [1]:
import numpy as np
import pandas as pd

In [2]:
# load the data
df = pd.read_csv("./glass.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [3]:
df.isna().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [4]:
df.corr()

RI        Na        Mg        Al        Si         K        Ca  \
RI    1.000000 -0.191885 -0.122274 -0.407326 -0.542052 -0.289833  0.810403   
Na   -0.191885  1.000000 -0.273732  0.156794 -0.069809 -0.266087 -0.275442   
Mg   -0.122274 -0.273732  1.000000 -0.481799 -0.165927  0.005396 -0.443750   
Al   -0.407326  0.156794 -0.481799  1.000000 -0.005524  0.325958 -0.259592   
Si   -0.542052 -0.069809 -0.165927 -0.005524  1.000000 -0.193331 -0.208732   
K    -0.289833 -0.266087  0.005396  0.325958 -0.193331  1.000000 -0.317836   
Ca    0.810403 -0.275442 -0.443750 -0.259592 -0.208732 -0.317836  1.000000   
Ba   -0.000386  0.326603 -0.492262  0.479404 -0.102151 -0.042618 -0.112841   
Fe    0.143010 -0.241346  0.083060 -0.074402 -0.094201 -0.007719  0.124968   
Type -0.164237  0.502898 -0.744993  0.598829  0.151565 -0.010054  0.000952   

            Ba        Fe      Type  
RI   -0.000386  0.143010 -0.164237  
Na    0.326603 -0.241346  0.502898  
Mg   -0.492262  0.083060 -0.744993  
Al    0.479404 -0.074402  0.598829  
Si   -0.102151 -0.094201  0.151565  
K    -0.042618 -0.007719 -0.010054  
Ca   -0.112841  0.124968  0.000952  
Ba    1.000000 -0.058692  0.575161  
Fe   -0.058692  1.000000 -0.188278  
Type  0.575161 -0.188278  1.000000

In [5]:
df.drop(['K','Ca'], axis=1, inplace=True)

In [9]:
# splitting the data into x and y
x = df.drop('Type', axis=1)
y = df['Type']

In [13]:
y.unique()

array([1, 2, 3, 5, 6, 7])

In [14]:
df['Type'].unique()

array([1, 2, 3, 5, 6, 7])

In [15]:
df['Type'].value_counts()

Type
2    76
1    70
7    29
3    17
5    13
6     9
Name: count, dtype: int64

In [17]:
# splitting the data into train and test set
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=123456)

In [33]:
# create and train the model
from sklearn.tree import DecisionTreeClassifier

model_dt = DecisionTreeClassifier(max_depth=3)
model_dt.fit(x_train, y_train)

from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(n_estimators=500, max_depth=6)
model_rf.fit(x_train, y_train)

RandomForestClassifier(max_depth=6, n_estimators=500)

In [34]:
# model evaluation
from sklearn.metrics import confusion_matrix

def confusion_matrix_funct(model, model_name):
    y_pred = model.predict(x_test)
    y_true = y_test

    print(f"Confusion Matrix for {model_name}= \n{confusion_matrix(y_true, y_pred)}")

confusion_matrix_funct(model_dt, "Decision Tree")
confusion_matrix_funct(model_rf, "Random Tree")

Confusion Matrix for Decision Tree= 
[[16  2  0  0  0  0]
 [ 7 12  0  4  0  0]
 [ 6  0  0  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  2  0  0]
 [ 1  1  0  0  0  9]]
Confusion Matrix for Random Tree= 
[[17  1  0  0  0  0]
 [ 4 16  0  2  1  0]
 [ 3  3  0  0  0  0]
 [ 0  1  0  4  0  0]
 [ 0  0  0  0  2  0]
 [ 1  1  0  0  0  9]]


In [35]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def model_evaluation(model, model_name):
    y_pred = model.predict(x_test)
    y_true = y_test

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    return model_name, accuracy, precision, recall, f1

In [36]:
result_df = pd.DataFrame([model_evaluation(model_dt, "Decision Tree"), model_evaluation(model_rf, "Random Forest")], columns=['Model','Accuracy','Precision','Recall score','F1 score'])
result_df

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Model  Accuracy  Precision  Recall score  F1 score
0  Decision Tree  0.646154   0.634965      0.646154  0.608482
1  Random Forest  0.738462   0.686676      0.738462  0.703453